name: aeson-compat
version: 0.3.0.0
synopsis: Compatibility layer for aeson
description: |
    Compatibility layer for @aeson@
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/aeson-compat
category: Web
tested-with: GHC==7.6.3, GHC==7.8.4, GHC==7.10.3
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base                     >=4.6  && <4.9
  - aeson                    >=0.7.0.6 && <0.11
  - attoparsec               >=0.12 && <0.14
  - bytestring               >=0.10 && <0.11
  - containers               >=0.5  && <0.6
  - exceptions               >=0.8  && <0.9
  - hashable                 >=1.2  && <1.3
  - scientific               >=0.3  && <0.4
  - text                     >=1.2  && <1.3
  - time                     >=1.4.2 && <1.7
  - unordered-containers     >=0.2  && <0.3
  - vector                   >=0.10 && <0.12

library:
  source-dirs: src
  other-modules:
    - Data.Aeson.Compat.Time

tests:
  aeson-compat-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - aeson-compat
      - tasty                 >=0.10 && <0.12
      - tasty-hunit           >=0.9  && <0.10
      - tasty-quickcheck      >=0.8  && <0.9
      - quickcheck-instances  >=0.3  && <0.4
