name: aeson-compat
version: 0.3.5.1
synopsis: Compatibility layer for aeson
description: |
    Compatibility layer for @aeson@
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/aeson-compat
category: Web
tested-with: GHC==7.6.3, GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base                     >=4.6  && <4.10
  - base-compat              >=0.6.0 && <0.10
  - aeson                    >=0.7.0.6 && <0.11.3
  - attoparsec               >=0.12 && <0.14
  - bytestring               >=0.10 && <0.11
  - containers               >=0.5  && <0.6
  - exceptions               >=0.8  && <0.9
  - hashable                 >=1.2  && <1.3
  - nats                     >=1 && <1.2
  - scientific               >=0.3  && <0.4
  - text                     >=1.2  && <1.3
  - time                     >=1.4.2 && <1.7
  - time-locale-compat       >=0.1.0.1 && <0.2
  - unordered-containers     >=0.2  && <0.3
  - vector                   >=0.10 && <0.12
  - semigroups               >=0.16.2.2 && <0.19
  - tagged                   >=0.7.3 && <0.9

library:
  source-dirs: src
  other-modules:
    - Data.Aeson.Compat.Time

tests:
  aeson-compat-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - aeson-compat
      - base-orphans          >=0.4.5 && <0.6
      - tasty                 >=0.10 && <0.12
      - tasty-hunit           >=0.9  && <0.10
      - tasty-quickcheck      >=0.8  && <0.9
      - QuickCheck            >=2.7.6 && <2.8.3
      - quickcheck-instances  >=0.3  && <0.3.13
